config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mission.urls')),
    path('', include('user.urls')),
    path('', include('exp.urls')),
    path('', include('thanks.urls')),
]

exp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # ミッションにいいねアクセスしたとき
    path('mission/<int:pk>/good/', views.MissionGood, name='mission-good'),
    # 参加するにアクセスしたとき
    path('mission/<int:pk>/join/', views.MissionJoin, name='mission-join'),
    # ミッションクリアにアクセスしたとき
    path('mission/<int:pk>/success/', views.MissionSuccess, name='mission-success'),
    # ミッション承認にアクセスされたとき
    path('mission/<int:pk>/approval/', views.MissionApproval, name='mission-approval'),
    # サンクス承認にアクセスされたとき
    path('thanks/<int:pk>/approval/', views.ThanksApproval, name='thanks-approval'),
    # サンクスにいいねアクセスしたとき
    path('thanks/<int:pk>/good/', views.ThanksGood, name='thanks-good'),
]

mission/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('mission/home/',views.MissionListView.as_view(),name='mission-home'),
     path('mission/new/',views.MissionCreateView.as_view(),name='mission-create'),
     path('mission/<int:pk>/',views.MissionDetailView.as_view(),name='mission-detail'),
     path('mission/<int:pk>/update',views.MissionUpdateView.as_view(),name='mission-update'),
     path('mission/mission_approval/',views.MissionWaitingListView.as_view(),name='mission-waiting'),
]

mission/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from user.models import Profile

EXAMPLE_FLG = (
    (0, '実践中'),
    (1, '達成'),
)
EXAMPLE_APPROVAL = (
    (0, '承認待ち'),
    (1, '承認済み'),
)
class Mission(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    mission_flg = models.IntegerField(choices=EXAMPLE_FLG, default=0)    # 達成状況(0:実践中 / 1:達成)
    cost_exp = models.IntegerField(default=3)                            # 作成時に消費されるポイント(使えていない)
    success_exp = models.IntegerField(default=0)                        # クリア報酬ポイント
    good_count = models.IntegerField(default=0)                          # いいね数
    participants = models.IntegerField(default=0)                        # 参加者数
    participants_limit = models.IntegerField(default=0)                  # 参加人数制限
    participants_list_text = models.CharField(max_length=200, default='')# 参加者リスト(文字列で保存)
    participants_list = models.ManyToManyField(Profile)                  # 参加者リスト(他対他)
    approval = models.IntegerField(choices=EXAMPLE_APPROVAL, default=0)  # 承認状況
    

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('mission-detail', kwargs={'pk': self.pk})
    

# いいねを押す人 / いいねを押されるMission
class Good_mission(models.Model):
    mission_good_giver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='mission_good_giver')
    good_mission = models.ForeignKey(Mission, on_delete=models.CASCADE)



user/models.py
from django.db import models
from django.contrib.auth.models import User

KUBUN_CHOICES = (
    ('1', '経営者'),
    ('2', '従業員'),
    ('3', '管理者'),
)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    kubun = models.CharField(verbose_name='区分',
                             max_length=2,
                             choices=KUBUN_CHOICES,)
    exp_total = models.IntegerField(verbose_name='経験値', default=10)
    mission_create_count = models.IntegerField(default=0)  # ミッション作成回数
    my_success_count = models.IntegerField(default=0)      # 自ら作成したミッションの達成数
    join_count = models.IntegerField(default=0)            # ミッション参加回数
    team_success_count = models.IntegerField(default=0)    # 参加したミッションの達成回数
    thanks_count = models.IntegerField(default=0)          # 感謝した回数
    thanked_count = models.IntegerField(default=0)         # 感謝された回数

    def __str__(self):
        return str(self.user)

mission/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)
from django.views.generic.edit import ModelFormMixin
from .models import Mission
from user.models import Profile
from . import models
from django.shortcuts import render
from exp.forms import MissionApprovalForm
from django.db.models import Q



class MissionListView(ListView):
    model = Mission
    template_name = 'mission/home.html'
    context_object_name = 'missions'
    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super(MissionListView, self).get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)  
        context["profile"] = profile
        return context

    def get_queryset(self):
        q_word = self.request.GET.get('query')

        if q_word:
            object_list = Mission.objects.filter(
                Q(author__username__icontains=q_word)|Q(participants_list__user__username__icontains=q_word)).order_by('-date_posted')
        else:
            object_list = Mission.objects.all().order_by('-date_posted')
        return object_list


class MissionDetailView(DetailView, ModelFormMixin):
    model = Mission
    template_name = 'mission/mission_detail.html'
    fields = ()

    def get_context_data(self, **kwargs):
        context = super(MissionDetailView, self).get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)  # ログインユーザーのプロフィール
        context.update({
            'form': MissionApprovalForm(**self.get_form_kwargs()),
            'profile' : profile,
        })
        return context
    

class MissionCreateView(LoginRequiredMixin, CreateView):
    model = Mission
    fields = ['title', 'content', 'participants_limit']

    def form_valid(self, form):
        form.instance.author = self.request.user
        profile = Profile.objects.get(user=self.request.user)  # 自分のプロフィール
        # mission = Mission.objects.get(pk=self.pk)
        profile.exp_total -= 1
        # profile.exp_total -= mission.cost_exp
        profile.mission_create_count += 1
        profile.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(MissionCreateView, self).get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)  
        context["profile"] = profile
        return context

            

class MissionUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Mission
    fields = ['title', 'content', 'participants_limit']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        mission = self.get_object()
        if self.request.user == mission.author:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super(MissionUpdateView, self).get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)  
        context["profile"] = profile
        return context



class MissionDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Mission
    success_url = '/'

    def test_func(self):
        mission = self.get_object()
        if self.request.user == mission.author:
            return True
        return False

class MissionWaitingListView(ListView):
    model = Mission
    template_name = 'mission/mission_waiting.html'
    context_object_name = 'missions'
    # paginate_by = 9
    ordering = ['-date_posted']

    def get_context_data(self, **kwargs):
        context = super(MissionWaitingListView, self).get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)  
        not_approval = Mission.objects.filter(approval=0) 
        context["profile"] = profile
        context['not_approval'] = not_approval
        return context


mission/templates/mission/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Mission</title>
    <link rel="stylesheet" type="text/css" href="{% static 'mission/css/style.css' %}">
    <script src="https://unpkg.com/react@16/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
</head>

<body>
    <a href="{% url 'expmain' %}">マイページ</a>
    <a>&emsp;</a>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">ログアウト</a>
        <a>&emsp;</a>
        <a href="{% url 'mission-home' %}">ミッション一覧</a>
        <a>&emsp;</a>
        <a href="{% url 'thanks-list' %}">サンクス一覧</a>
        <a>&emsp;</a>
        {% if profile.get_kubun_display == '経営者' or profile.get_kubun_display == '管理者' %}
            <a href="{% url 'management' %}">メンバー管理</a>
            <a>&emsp;</a>
            <a href="{% url 'mission-waiting' %}">承認待ち</a>
            <a>&emsp;</a>
        {% endif %}        
    {% else %}
        <a href="{% url 'login' %}">ログイン</a>
        <a>&emsp;</a>
        <a href="{% url 'signup' %}">アカウント作成</a>
    {% endif %}

    <div id="root"></div>
    <script type="text/babel">
        (() => {
            const name = 'yoshiki';
            ReactDOM.render(
                <p>Hello!{name}</p>,
                document.getElementById('root')
            );

        })();
    </script>


    {% block body %}
    {% endblock body %}




<!-- 
    <div>

        {% for mission in missions %}
        <h1>{{ mission.title }} <small>written by:
            </small><span>{{ mission.author }}</span></h1>
        <ul>
            <li>{{ mission.content }}</li>
        </ul>
        <hr>
        {% endfor %}

    </div> -->


</body>

</html>

mission/templates/mission/home.html
{% extends 'mission/base.html' %}
{% block body %}

<!-- {% if user.is_authenticated %} -->
<h1>ミッション一覧</h1>
<!-- {% endif %} -->

<div>

    <form action="{% url 'mission-create' %}">
        <button type="submit">New MISSION</button>
    </form>

    <form action="" method="get">
        <input name="query" value="{{ request.GET.query }}" type="text">
        <button type="submit">検索する</button>
    </form>

    {% for mission in missions %}
        {% if mission.get_approval_display == '承認済み' %}
            <hr>
            <h1><a href="{% url 'mission-detail' mission.id %}">{{ mission.title }}</a></h1>
            <ul>
                <li>投稿時間：<b>{{ mission.date_posted }}</b></li>
                <li>依頼者：<b>{{ mission.author }}</b></li>
                <li>達成状況：<b>{{ mission.get_mission_flg_display }}</b></li>
                <li>達成報酬EXP：<b>{{ mission.success_exp }}</b>exp</li>
                <li>いいね数：<b>{{ mission.good_count }}</b></li>
                <li>参加人数：<b>{{ mission.participants }}</b>/{{ mission.participants_limit }} 人</li>
            </ul>
        {% endif %}
    {% endfor %}

    
    {% if page_obj.has_previous %}
        <a href="{% url 'mission-home' %}">&laquo;first</a>
        <a href="?page={{page_obj.previous_page_number}}">&laquo;prev</a>
    {% endif %}
        <span>[ {{ page_obj.number }} / {{ page_obj.paginator.num_pages }} ]</span>
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number}}">next&raquo;</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last&raquo;</a>
    {% endif %}
        
    
</div>
{% endblock body %}

mission/templates/mission/mission_detail.html
{% extends 'mission/base.html' %}

{% block body %}

<center>
    <h1>「{{ object.title }} 」<small>依頼者:</small><span>{{ object.author }}</span></h1>
    <p>{{ object.date_posted|date:'Y-m-d P' }}</p>
    <p> {{ object.content }}</p>
    <hr>
    <b><p>【 {{ object.get_approval_display }} 】</p></b>
    <p>クリア報酬EXP：<b>{{ object.success_exp}}</b>exp</p>
    <p>達成状況：<b>{{ object.get_mission_flg_display }}</b></p>
    <p>いいね！：<b>{{ object.good_count}}</b></p>
    <p>最大参加人数：<b>{{ object.participants_limit }}</b>人まで</p>
    <p>現在参加人数：<b>{{ object.participants }}</b>人</p>
    <!-- <p>参加人数：<b>{{ object.participants }}</b>/{{ object.participants_limit }} 人</p> -->
    {% if object.participants > 0 %}
    <p>参加者：<b>
        {% for item in mission.participants_list.all %}
            {% if forloop.last %}
                {{ item.user }}さん 
            {% else %}
                {{ item.user }}さん、
            {% endif %}
        {% endfor %}
    </b></p>
    {% endif %}
    
    {% if messages %}      
        {% for message in messages %}
            <h4>{{ message }}</h4>
        {% endfor %}      
    {% endif %}           
</center>


{% if object.author != request.user and object.mission_flg == 0 %}
    <form action="{% url 'mission-good' object.pk %}">
        {% csrf_token %}
        <input type="submit" value="いいね">
    </form>
    <br>     
    <form action="{% url 'mission-join' object.pk %}">
        {% csrf_token %}
        {% if profile in mission.participants_list.all %}
            <input type="submit" value="脱退">
        {% elif mission.participants_limit > mission.participants %}
            <input type="submit" value="参加">
        {% else %}
            <p>参加者は定員に達しました。</p>
        {% endif %}      
    </form>
{% endif %}

<!-- ログイン中のユーザーが、ミッションの作成者であり未達成の場合 -->
{% if request.user == object.author and object.mission_flg == 0 %} 
    <!-- 承認済みの場合 -->
    {% if object.approval == 1 %}
    <form action="{% url 'mission-success' object.pk %}">
        {% csrf_token %}
        <input type="submit" value="ミッションクリア">   
    </form>
    {% endif %}     
    <form action="{% url 'mission-update' object.pk %}">
        {% csrf_token %}
        <input type="submit" value="Mission内容修正">
    </form>
{% endif %}
<br>

<!-- 承認待ちのミッションで、経営者か管理者だった場合「承認」ボタンを表示する -->
{% if profile.get_kubun_display == '経営者' or profile.get_kubun_display == '管理者' %}
{% if object.approval == 0 %}
    <table>
        <form action="{% url 'mission-approval' object.pk %}" method="POST">
            {% csrf_token %}
            <tr><th>クリア報酬EXP</th><td>{{ form.success_exp }}</td></tr>
            <tr><td><input type="submit" value="承認"></td></tr>
        </form>
    </table>
{% endif %}
{% endif %}   

{% endblock body %}

mission/templates/mission/mission_form.html
{% extends 'mission/base.html' %}

{% block body %}


<div>
    <h1>ミッション作成</h1>
    
    {% if profile.exp_total <= 0 %}
        <p>※所有EXPが足りません</p>
        <p>現在所有EXP：{{ profile.exp_total }}exp</p>
    {% endif %}      
        
</div>
{% if profile.exp_total > 0 %}
    <div>
        <table>
            <form method='POST' role="form" action="#">
                {% csrf_token %}
                <tr><th>タイトル</th><td>{{ form.title }}</td></tr>
                <tr><th>内容</th><td>{{ form.content }}</td></tr>
                <tr><th>参加人数制限</th><td>{{ form.participants_limit }}人</td></tr>
                <tr><th></th><td><input type="submit" value="作成"></td></tr>
            </form>
        </table>
    </div>
{% endif %}

{% endblock body %}

mission/templates/mission/mission_waiting.html
{% extends 'mission/base.html' %}

{% block body %}
            
<h1>承認待ちのミッション</h1>

<div>
    <h3>承認待ちのミッション / <a href="{% url 'thanks-waiting' %}">承認待ちのサンクス</a></h3>

    {% for mission in missions %}
        {% if mission.get_approval_display == '承認待ち' %}
            <h1><a href="{% url 'mission-detail' mission.id %}">{{ mission.title }}</a></h1>
            <ul>
                <li>依頼者：<b>{{ mission.author }}</b></li>
                <li>達成状況：<b>{{ mission.get_mission_flg_display }}</b></li>
                <li>時間：<b>{{ mission.date_posted }}</b></li>
                <li>獲得EXP：<b>{{ mission.success_exp }}</b>exp</li>
                <li>現在いいね数：<b>{{ mission.good_count }}</b></li>
                <li>参加者数：<b>{{ mission.participants }}</b>人</li>
            </ul>
            <hr>
        {% endif %}
    {% endfor %}

    {% if not not_approval %}
        <hr>
        <p>現在、承認待ちのミッションはありません。</p>
    {% endif %}
        
    
<!-- 承認で表示するミッション数が変わるとページネーションがズレる -->
    <!-- {% if page_obj.has_previous %}
        <a href="{% url 'mission-waiting' %}">&laquo;first</a>
        <a href="?page={{page_obj.previous_page_number}}">&laquo;prev</a>
    {% endif %}
        <span>[ {{ page_obj.number }} / {{ page_obj.paginator.num_pages }} ]</span>
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number}}">next&raquo;</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last&raquo;</a>
    {% endif %} -->
        
    
</div>
{% endblock body %}
    